Arithmetic uzdevumi
LaurisMih/C_Sharp pull request #4
Opened 2022-07-29 07:44 UTC by LaurisMih

2022-07-31 20:17 UTC, ausmoons requested changes

2022-07-31 20:17 UTC, ausmoons commented on .gitignore
> +/csharp-basics/exercises/*/*/bin/*
Tu apskatījies kādus failus esi pievienojis? Gitignore tikai mainā vai atsevisķā branchā labot.

2022-07-31 20:22 UTC, LaurisMih commented on .gitignore
> +/csharp-basics/exercises/*/*/bin/*
Kas man jāizdara ar .gitignore ?

2022-08-01 18:02 UTC, ausmoons commented on .gitignore
> +/csharp-basics/exercises/*/*/bin/*
Kādā ziņā? Kādu rezultātu tu gribi?

2022-08-01 18:08 UTC, LaurisMih commented on .gitignore
> +/csharp-basics/exercises/*/*/bin/*
Sveiki, es pārtaisiju PR, varat lūdzu apskatīt ArithmeticV2. Tur itkā viss ir ok ar .gitignore failu,jo šeit es kaut ko saspaidiju pašā sākumā

2022-08-01 18:08 UTC, closed without merging