Loops
LaurisMih/C_Sharp pull request #8
Opened 2022-08-07 19:06 UTC by LaurisMih

2022-08-10 13:33 UTC, LaurisMih commented
Exercise 5 es netīšām pievienoju Exercise 7, bet tas nav gatavs 7 uzdevums. Gatavs variants būs atsevišķi Exercise 7. Atvainojiet par neērtībām

2022-08-10 19:09 UTC, ausmoons commented
> Exercise 5 es netīšām pievienoju Exercise 7, bet tas nav gala rezultāts. Gatavs variants būs atsevišķi Exercise 7. Atvainojiet par neērtībām

Tad PR vēl nav gatavs?

2022-08-10 20:09 UTC, LaurisMih commented
PR ir gatavs

2022-08-10 20:15 UTC, ausmoons commented
> PR ir gatavs
Gatavs variants būs atsevišķi Exercise 7 -- tu kaut ko vēl taisīsi?

2022-08-10 20:58 UTC, LaurisMih commented
> > PR ir gatavs
> > Gatavs variants būs atsevišķi Exercise 7 -- tu kaut ko vēl taisīsi?

Tas gatavais 7 uzdevums ir Exercise 7

2022-08-12 19:14 UTC, ausmoons requested changes

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 3/Program.cs
> +            int Min = 0;
min, max, jo iekš metodes

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 4/Program.cs
> +           // todo - use foreach
Lieks komentārs un tab nav ok

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 6/Program.cs
> +
Pietiek ar vienu tukšu rindu

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 6/Program.cs
> +                for (int lines = 1; lines <= 20; lines++)
tukša rind pēc }

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 7/Program.cs
> +
Lieka tukša rinda

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 7/Program.cs
> +                if (userInput == "start" && userNumber == 1)
else if

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 7/Program.cs
> +
Lieka tukša rinda

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 8/Program.cs
> +                for (int a = i; a <= (art * 3 + 2) - (4 * i) + i; a++)
Tukša rinda pēc }

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 9/Program.cs
> +                if (sum == result)
tab nav ok

2022-08-12 19:14 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 9/Program.cs
> +                   // Console.WriteLine();
?

2022-08-19 18:30 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/Exercise 9/Program.cs
> +                   // Console.WriteLine();
Kad tu plāno labot komentārus?

2022-08-20 08:30 UTC, ausmoons approved these changes

2022-08-20 09:42 UTC, merged